mailer:
  delivery_method: :smtp
  smtp_settings:
    address: <%= ENV['SMTP_ADDRESS'] %>
    port: <%= (ENV['SMTP_PORT'] || 0).to_i %>
    domain: <%= ENV['SMTP_DOMAIN'] %>
    user_name: <%= ENV['SMTP_USERNAME'] %>
    password: <%= ENV['SMTP_PASSWORD'] %>
    authentication: <%= (ENV['SMTP_AUTHENTICATION'] || 'login').to_sym %>
    enable_starttls_auto: <%= ENV['SMTP_ENABLE_STARTTLS_AUTO'] == 'true' %>